### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by samuel-lucas6** [orthecreedence/cl-sodium#10]
Hi @orthecreedence, I'm currently trying to tidy up the bindings linked on the libsodium website. If this library is still maintained, then please let me know; otherwise, the link to this library will [likely](https://github.com/jedisct1/libsodium-doc/pull/156#issuecomment-1067834246) be removed from the [bindings](https://doc.libsodium.org/bindings_for_other_languages) page to help users find up to date and maintained bindings.

**Comment by orthecreedence** [comment]
Hello! This is no longer actively maintained. I accept PRs, but other than that I'm not keeping up with any libsodium changes.

**Comment by samuel-lucas6** [comment]
Thanks for getting back to me.
